# This file was generated by the timeline_keeper install generator.
# You must edit this file to match your method of determining a link to
# external media.

module TimelineKeeperHelper

  # The url_for_external_media helper accepts an event and returns a full URL to a resource
  def url_for_external_media(event)
    "http://d.lib.ncsu.edu/collections/catalog/#{event.media_filename}"
  end

end